# Site settings
title: ww's Personal Blog
email: 1415089774@qq.com
description: ww's Ideas & Blogs
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: wwfighting
permalink: /:year/:month/:day/:title/
# this is the url root of the view source link on the footer page.
viewsourceroot: https://github.com/wwfighting/wwfighting.github.io
# this is the url root of the create page link on the footer page.
newsourceroot: https://wwfighting.github.io
#########################################
# for duoshuo.com commenting system, uncomment following line if you do not want to include duoshuo.com. 
duoshuo_shortname: wwfighting
duoshuo_url: "http://wwfighting.github.io"
# disqus.com commenting system. please note that it is exclusive with duoshuo.com
#disqus_shortname: ww
#disqus_url: "http://wwfighting.github.io"
#########################################

# Build settings
markdown: kramdown

# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false
